services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - billing-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: unless-stopped
    volumes:
      - ./observability/otel-collector/otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    networks:
      - billing-network

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns,ses,s3
      - DEFAULT_REGION=us-east-1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - "./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"

  invoices-postgres:
    image: postgres:16.0
    container_name: invoices-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${INVOICE_DB}
      POSTGRES_USER: ${INVOICE_USER}
      POSTGRES_PASSWORD: ${INVOICE_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - invoices_postgres_data:/var/lib/postgresql/data
    networks:
      - billing-network

  payments-postgres:
    image: postgres:16.0
    container_name: payments-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PAYMENT_DB}
      POSTGRES_USER: ${PAYMENT_USER}
      POSTGRES_PASSWORD: ${PAYMENT_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data
    networks:
      - billing-network

  subscriptions-postgres:
    image: postgres:16.0
    container_name: subscriptions-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${SUBSCRIPTION_DB}
      POSTGRES_USER: ${SUBSCRIPTION_USER}
      POSTGRES_PASSWORD: ${SUBSCRIPTION_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - subscription_postgres_data:/var/lib/postgresql/data
    networks:
      - billing-network

  customers-postgres:
    image: postgres:16.0
    container_name: customers-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${CUSTOMERS_DB}
      POSTGRES_USER: ${CUSTOMERS_USER}
      POSTGRES_PASSWORD: ${CUSTOMERS_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - billing-network

  authentication-postgres:
    image: postgres:16.0
    container_name: authentication-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${AUTHENTICATION_DB}
      POSTGRES_USER: ${AUTHENTICATION_USER}
      POSTGRES_PASSWORD: ${AUTHENTICATION_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - authentication_postgres_data:/var/lib/postgresql/data
    networks:
      - billing-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: billing-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - billing-network

volumes:
  postgres_data:
    driver: local
  authentication_postgres_data:
    driver: local
  subscription_postgres_data:
    driver: local
  payment_postgres_data:
    driver: local
  invoices_postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  billing-network:
    driver: bridge
    name: billing-network
