services:

  config-service:
    container_name: config-service
    build: ./config-service
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      - EUREKA_CLIENT_ENABLED=false
      - OTLP_METRICS_EXPORT_URL=${OTLP_METRICS_EXPORT_URL}
      - OTLP_LOGGING_EXPORT_URL=${OTLP_LOGGING_EXPORT_URL}
    networks:
      - billing-network

  eureka-service:
    container_name: eureka-service
    build: ./eureka-service
    restart: unless-stopped
    ports:
      - "8761:8761"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:${CONFIG_SERVER_URL}
      - OTLP_METRICS_EXPORT_URL=${OTLP_METRICS_EXPORT_URL}
      - OTLP_LOGGING_EXPORT_URL=${OTLP_LOGGING_EXPORT_URL}
      - OTLP_TRACING_EXPORT_URL=${OTLP_TRACING_EXPORT_URL}
    depends_on:
      - config-service
    networks:
      - billing-network

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:${CONFIG_SERVER_URL}
      - EUREKA_ZONE_URL=${EUREKA_ZONE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - OTLP_METRICS_EXPORT_URL=${OTLP_METRICS_EXPORT_URL}
      - OTLP_LOGGING_EXPORT_URL=${OTLP_LOGGING_EXPORT_URL}
      - OTLP_TRACING_EXPORT_URL=${OTLP_TRACING_EXPORT_URL}
    depends_on:
      - config-service
      - eureka-service
    networks:
      - billing-network

  authentication-service:
    container_name: authentication-service
    build: ./authentication-service
    restart: unless-stopped
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:${CONFIG_SERVER_URL}
      - EUREKA_ZONE_URL=${EUREKA_ZONE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - AUTHENTICATION_SERVICE_URL_DATABASE=${AUTHENTICATION_SERVICE_URL_DATABASE}
      - BILLING_ENGINE_DB_USER=${BILLING_ENGINE_DB_USER}
      - BILLING_ENGINE_DB_PASSWORD=${BILLING_ENGINE_DB_PASSWORD}
      - AUTHENTICATION_SERVICE_CLIENT_ID=${AUTHENTICATION_SERVICE_CLIENT_ID}
      - AUTHENTICATION_SERVICE_SECRET=${AUTHENTICATION_SERVICE_SECRET}
      - OTLP_METRICS_EXPORT_URL=${OTLP_METRICS_EXPORT_URL}
      - OTLP_LOGGING_EXPORT_URL=${OTLP_LOGGING_EXPORT_URL}
      - OTLP_TRACING_EXPORT_URL=${OTLP_TRACING_EXPORT_URL}
    depends_on:
      - config-service
      - eureka-service
    networks:
      - billing-network

  customers-service:
    container_name: customers-service
    build: ./customers-service
    restart: unless-stopped
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:${CONFIG_SERVER_URL}
      - EUREKA_ZONE_URL=${EUREKA_ZONE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - CUSTOMERS_SERVICE_URL_DATABASE=${CUSTOMERS_SERVICE_URL_DATABASE}
      - BILLING_ENGINE_DB_USER=${BILLING_ENGINE_DB_USER}
      - BILLING_ENGINE_DB_PASSWORD=${BILLING_ENGINE_DB_PASSWORD}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - OTLP_METRICS_EXPORT_URL=${OTLP_METRICS_EXPORT_URL}
      - OTLP_LOGGING_EXPORT_URL=${OTLP_LOGGING_EXPORT_URL}
      - OTLP_TRACING_EXPORT_URL=${OTLP_TRACING_EXPORT_URL}
    depends_on:
      - config-service
      - eureka-service
    networks:
      - billing-network

  subscription-service:
    container_name: subscription-service
    build: ./subscription-service
    restart: unless-stopped
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:${CONFIG_SERVER_URL}
      - EUREKA_ZONE_URL=${EUREKA_ZONE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - SUBSCRIPTION_SERVICE_URL_DATABASE=${SUBSCRIPTION_SERVICE_URL_DATABASE}
      - BILLING_ENGINE_DB_USER=${BILLING_ENGINE_DB_USER}
      - BILLING_ENGINE_DB_PASSWORD=${BILLING_ENGINE_DB_PASSWORD}
      - SUBSCRIPTION_SERVICE_CLIENT_ID=${SUBSCRIPTION_SERVICE_CLIENT_ID}
      - SUBSCRIPTION_SERVICE_SECRET=${SUBSCRIPTION_SERVICE_SECRET}
      - AWS_REGION=${AWS_REGION}
      - AWS_URI=${AWS_URI}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - ACTIVE_SUBSCRIPTION_QUEUE=${ACTIVE_SUBSCRIPTION_QUEUE}
      - DEACTIVATE_SUBSCRIPTION_QUEUE=${DEACTIVATE_SUBSCRIPTION_QUEUE}
      - SUBSCRIPTION_CREATED_TOPIC=${SUBSCRIPTION_CREATED_TOPIC}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - OTLP_METRICS_EXPORT_URL=${OTLP_METRICS_EXPORT_URL}
      - OTLP_LOGGING_EXPORT_URL=${OTLP_LOGGING_EXPORT_URL}
      - OTLP_TRACING_EXPORT_URL=${OTLP_TRACING_EXPORT_URL}
    depends_on:
      - config-service
      - eureka-service
      - localstack
    networks:
      - billing-network

  payment-service:
    container_name: payment-service
    build: ./payment-service
    restart: unless-stopped
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:${CONFIG_SERVER_URL}
      - EUREKA_ZONE_URL=${EUREKA_ZONE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - PAYMENT_SERVICE_URL_DATABASE=${PAYMENT_SERVICE_URL_DATABASE}
      - BILLING_ENGINE_DB_USER=${BILLING_ENGINE_DB_USER}
      - BILLING_ENGINE_DB_PASSWORD=${BILLING_ENGINE_DB_PASSWORD}
      - AWS_REGION=${AWS_REGION}
      - AWS_URI=${AWS_URI}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - PROCESS_PAYMENT_QUEUE=${PROCESS_PAYMENT_QUEUE}
      - PAYMENT_PROCESSING_DLQ=${PAYMENT_PROCESSING_DLQ}
      - PAYMENT_APPROVED_TOPIC=${PAYMENT_APPROVED_TOPIC}
      - PAYMENT_FAILED_TOPIC=${PAYMENT_FAILED_TOPIC}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SIGN=${STRIPE_WEBHOOK_SIGN}
      - OTLP_METRICS_EXPORT_URL=${OTLP_METRICS_EXPORT_URL}
      - OTLP_LOGGING_EXPORT_URL=${OTLP_LOGGING_EXPORT_URL}
      - OTLP_TRACING_EXPORT_URL=${OTLP_TRACING_EXPORT_URL}
    depends_on:
      - config-service
      - eureka-service
      - localstack
    networks:
      - billing-network

  invoice-service:
    container_name: invoice-service
    build: ./invoice-service
    restart: unless-stopped
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:${CONFIG_SERVER_URL}
      - EUREKA_ZONE_URL=${EUREKA_ZONE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - INVOICE_SERVICE_URL_DATABASE=${INVOICE_SERVICE_URL_DATABASE}
      - BILLING_ENGINE_DB_USER=${BILLING_ENGINE_DB_USER}
      - BILLING_ENGINE_DB_PASSWORD=${BILLING_ENGINE_DB_PASSWORD}
      - AWS_REGION=${AWS_REGION}
      - AWS_URI=${AWS_URI}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - GENERATE_NEW_INVOICE_QUEUE=${GENERATE_NEW_INVOICE_QUEUE}
      - INVOICE_CREATED_QUEUE=${INVOICE_CREATED_QUEUE}
      - OTLP_METRICS_EXPORT_URL=${OTLP_METRICS_EXPORT_URL}
      - OTLP_LOGGING_EXPORT_URL=${OTLP_LOGGING_EXPORT_URL}
      - OTLP_TRACING_EXPORT_URL=${OTLP_TRACING_EXPORT_URL}
    depends_on:
      - config-service
      - eureka-service
      - localstack
    networks:
      - billing-network

  notification-service:
    container_name: notification-service
    build: ./notification-service
    restart: unless-stopped
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:${CONFIG_SERVER_URL}
      - EUREKA_ZONE_URL=${EUREKA_ZONE_URL}
      - AWS_REGION=${AWS_REGION}
      - AWS_URI=${AWS_URI}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - INTERNAL_SERVICE_EMAIL=${INTERNAL_SERVICE_EMAIL}
      - NOTIFY_SUBSCRIPTION_QUEUE=${NOTIFY_SUBSCRIPTION_QUEUE}
      - NOTIFY_PAYMENT_APPROVED=${NOTIFY_PAYMENT_APPROVED}
      - NOTIFY_PAYMENT_FAILED=${NOTIFY_PAYMENT_FAILED}
      - INVOICE_CREATED_QUEUE=${INVOICE_CREATED_QUEUE}
      - OTLP_METRICS_EXPORT_URL=${OTLP_METRICS_EXPORT_URL}
      - OTLP_LOGGING_EXPORT_URL=${OTLP_LOGGING_EXPORT_URL}
      - OTLP_TRACING_EXPORT_URL=${OTLP_TRACING_EXPORT_URL}
    depends_on:
      - config-service
      - eureka-service
      - localstack
    networks:
      - billing-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - otel-collector
      - loki
      - tempo
    networks:
      - billing-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    networks:
      - billing-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: unless-stopped
    volumes:
      - ./observability/otel-collector/otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    networks:
      - billing-network

  loki:
    image: grafana/loki:3.1.1
    container_name: loki
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./observability/loki/loki-config.yml:/etc/loki/loki-config.yml
      - loki_data:/loki
    networks:
      - billing-network

  tempo:
    image: grafana/tempo:2.6.1
    container_name: tempo
    restart: unless-stopped
    command: [ "-config.file=/etc/tempo/tempo-config.yml" ]
    ports:
      - "3200:3200"
    volumes:
      - ./observability/tempo/tempo-config.yml:/etc/tempo/tempo-config.yml
      - tempo_data:/var/tempo
    networks:
      - billing-network

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns,ses,s3
      - DEFAULT_REGION=us-east-1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - "./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
    networks:
      - billing-network

volumes:
  grafana_data:
    driver: local
  loki_data:
    driver: local
  tempo_data:
    driver: local

networks:
  billing-network:
    driver: bridge
    name: billing-network
